---
title: "ISSF Public Engagement Award"
author: "Bethany Dearlove"
date: "2014-09-11"
categories: [awards, outreach, University of Cambridge]
---

I'm thrilled to announce that I've won an [ISSF Public Engagement Award](https://www.medschl.cam.ac.uk/issf-prize-winners/) from the School of Clinical Medicine at the University of Cambridge. From the press release on the Department of Veterinary Medicine's website:

> Post-doctoral researcher Bethany Dearlove has recently won an ISSF Public Engagement award of £500 to develop her *Learning is infectious: pass it on* kit of activities aimed at introducing primary age school children to how genetic sequencing can be used to understand the spread of infectious disease. This success follows on from her taking second place in the Infectious Diseases zone in the final of *I'm a Scientist, Get me out of here*, for which her *Learning is infectious* kit was originally conceived. The competition, which took place in June, is an online X factor style event that offers school students the opportunity to interact with scientists. During a series of fast-paced chat sessions students challenged Bethany and her fellow scientists to explain their research and beyond in both an engaging and accessible way, voting for their favourites by process of elimination -- the winner taking £500 for a public engagement activity of their choice. Over the course of two weeks, Bethany interacted with students from eight schools, and in addition to the chats, answered over 100 long-form 'ASK' questions. "Although I was disappointed to fall at the last hurdle in *I'm a Scientist*, I was thrilled that the Wellcome Trust ISSF Public Engagement Competition Committee saw value in my project, and I'm looking forward to taking my research into local schools and beyond."
